<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JobDescription;

class JobDescriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['team' => 'A/B', 'description' => 'Melakukan perbaikan mesin', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat dan input pebaikan mesin [report cardty]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Admin', 'description' => 'Membuat suggestion system [ide perbaikan]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat suggestion system [ide perbaikan]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat pesanan sparepart untuk perbaikan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Melakukan perbaikan sparepart rusak', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Melakukan pengambilan backup machine & penggantian battery mesin', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Merapikan manual book di mesin [tersedia & update]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF"]'],
            ['team' => 'A/B', 'description' => 'Merawat tool yang digunakan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan 5S di area maintenance', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'Admin', 'description' => 'Melakukan 5S di area maintenance', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Support pembuatan report 1 jam problem dan chokotei', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melaksanakan WO [Work Order] instruksi dari atasan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membantu dan bekerjasama dengan team TPM dalam perbaikan/perawatan mesin', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Memimpin proses perbaikan mesin', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Konfirmasi inputing laporan perbaikan mesin dari member', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan inventory peralatan digunakan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat rangkuman perbaikan mesin setiap hari', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Menganalisa mesin yang belum diketahui akar masalahnya', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Merekap pemakaian pergantian sparepart baru', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Memberikan masukan kepada tim TPM', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Admin', 'description' => 'Memberikan masukan kepada tim TPM', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat laporan perbaikan mesin 1 h over', 'units' => '["OP", "CLERK", "MOP", "SL"]'],
            ['team' => 'A/B', 'description' => 'Support penyelesaian masalah mesin', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Merangkum masalah yang belum diketahui akar masalahnya', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Memperbaharui data perbaikan mesin [Cardty] setelah diketemukan akar masalah', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Support asa ichi meeting dengan produksi', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Control laptop, software dan kabel untuk perbaikan mesin', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Kontrol hoshin maintenance', 'units' => '["STL", "UH"]'],
            ['team' => 'Admin', 'description' => 'Membuat laporan bulanan maintenance [Kyoudom Dosu, 1h Over dan MTTR]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Membuat dan kontrol pekerjaan maintenance [Klarifikasi setiap laporan]', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Kontrol dokumen yang berkaitan dengan IATF dan ISO14001', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Support audit IATF dan ISO14001', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan kalibrasi mesin secara peridik [tightening & press fit process]', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Kontrol cost expense maintenance [sparepart]', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Membuat jadwal dan memberikan pelatihan kepada anggota maintenance', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Memperbaharui keterampilan dan kompetensi [hard skill dan soft skill] secara reguler', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan meeting internal maintenance', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Membuat PR internal function', 'units' => '["STL", "UH"]'],
            ['team' => 'Admin', 'description' => 'Membuat laporan kehadiran dan lembur', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Data entry maintenance pada Digimon system [Cardty]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Admin', 'description' => 'Memperbaharui laporan di maintenance board', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Admin', 'description' => 'Membagikan informasi dari departement lain untuk event di JID', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Mengontrol dan membuat jadwal penyelesaian WO dari Function Head', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Membuat Instruksi Kerja, One point lesson untuk maintenance [perbaikan, setting, dll]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'A/B', 'description' => 'Memperbaharui support list untuk maintenance [JJP, JTAP, Maker, Support Maker]', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan kaizen MUDA, NG ratio, penghematan energi [Safety, Environtment & Cost]', 'units' => '["STL", "UH"]'],
            ['team' => 'A/B', 'description' => 'Melakukan tinjauan aktivitas setiap 3 bulan', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Overhaul idle mesin', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Memperbaiki peralatan spesial [Unimar, Spindle, Wheelhead]', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat data peralatan spesial untuk peralatan OH', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat jadwal & progress OH', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat laporan hasil Overhaul', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat prosedur, instruksi kerja overhaul dan repair peralatan spesial', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat perencanaan pembiayaan operasional Overhaul team', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Mengontrol biaya overhaul dan repair peralatan', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat dan mengontrol sparepart OH dan repair peralatan', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Melakukan follow up setelah mesin/peralatan di OH/repair 1 bulan setelah running', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat laporan bulanan hasil pekerjaan di team Overhaul', 'units' => '["STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Merawat dan memelihara peralatan kerja', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Merawat dan memelihara peralatan kerja', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'TPM', 'description' => 'Membuat laporan hasil pekerjaan setiap hari kepada atasan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat laporan hasil pekerjaan setiap hari kepada atasan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat laporan hasil pekerjaan setiap hari kepada atasan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membantu team MTC/TPM dalam perbaikan/perawatan mesin', 'units' => '["OP", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melaporkan hasil pekerjaan pada jam lembur sehari setelahnya', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Melaporkan hasil pekerjaan pada jam lembur sehari setelahnya', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Melaporkan hasil pekerjaan pada jam lembur sehari setelahnya', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL"]'],
            ['team' => 'TPM', 'description' => 'Melaporkan setiap menemukan ketidaksesuaian di area/diluar pekerjaan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Melaporkan setiap menemukan ketidaksesuaian di area/diluar pekerjaan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Melaporkan setiap menemukan ketidaksesuaian di area/diluar pekerjaan', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL"]'],
            ['team' => 'TPM', 'description' => 'Menjalankan program dan menjaga 5S setiap hari ditempat kerja', 'units' => '["OP", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Menjalankan program dan menjaga 5S setiap hari ditempat kerja', 'units' => '["OP", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Menjalankan program dan menjaga 5S setiap hari ditempat kerja', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Membuat suggestion system [ide perbaikan]', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat suggestion system [ide perbaikan]', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat suggestion system [ide perbaikan]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL"]'],
            ['team' => 'TPM', 'description' => 'Membuat jadwal dan memberikan pelatihan kepada anggota maintenance', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat jadwal dan memberikan pelatihan kepada anggota maintenance', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'TPM', 'description' => 'Memperbaharui keterampilan dan kompetensi [hard skill dan soft skill] secara reguler', 'units' => '["STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melakukan kaizen MUDA, NG ratio, penghematan energi [Safety, Environtment & Cost]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Melakukan kaizen MUDA, NG ratio, penghematan energi [Safety, Environtment & Cost]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Melakukan kaizen MUDA, NG ratio, penghematan energi [Safety, Environtment & Cost]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Membuat jadwal TPM', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Data entry TPM dan OH pada Digimon system', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melakukan koordinasi dengan team atau departemen lain dalam melaksanakan aktifitas', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Melakukan koordinasi dengan team atau departemen lain dalam melaksanakan aktifitas', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Melakukan koordinasi dengan supplier dalam rangka support aktifitas Overhoul', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Mengkaji ulang prosedur, aturan, instruksi kerja di area OH', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'TPM', 'description' => 'Kontrol Hoshin TPM', 'units' => '["STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Membuat laporan TPM [internal & Eksternal]', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'TPM', 'description' => 'Membuat dan kontrol pekerjaan maintenance [Klarifikasi setiap laporan]', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Membuat dan kontrol pekerjaan maintenance [Klarifikasi setiap laporan]', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Kontrol dokumen yang berkaitan dengan IATF dan ISO14001', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Kontrol dokumen yang berkaitan dengan IATF dan ISO14001', 'units' => '["SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Support audit IATF dan ISO14001', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Support audit IATF dan ISO14001', 'units' => '["SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Membuat dan memperbaharui checksheet TPM setiap mesin', 'units' => '["SL", "SF", "STL"]'],
            ['team' => 'TPM', 'description' => 'Menyusun program pelatihan TPM untuk member produksi', 'units' => '["SL", "SF", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melaksanakan WO [Work Order] instruksi dari atasan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'Overhoul', 'description' => 'Melaksanakan WO [Work Order] instruksi dari atasan', 'units' => '["OP", "MOP", "SL", "SF", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Melayani permintaan SM & SP', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL"]'],
            ['team' => 'SM-SP', 'description' => 'Mengontrol dan memperbarui stok', 'units' => '["STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Revisi code, alamat atau parameter lain untuk SM dan SP', 'units' => '["STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Mengemas ulang oli dari drum ke jerigen', 'units' => '["OP", "CLERK"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat forecast tool [regrinding]', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat submaterial forecase', 'units' => '["SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Menindaklanjuti permintaan penawaran dan pengiriman dari pemasok', 'units' => '["STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat PR SM dan SP', 'units' => '["SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Menindaklanjuti pembaruan stok dari pemasok', 'units' => '["SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Mengontrol dan membuat jadwal penyelesaian WO dari Function Head', 'units' => '["STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Pembaruan Andon system', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Perbaikan masalah Andon', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat laporan cost meeting submaterial', 'units' => '["STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melakukan meeting internal unit', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'Overhoul', 'description' => 'Melakukan meeting internal unit', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Melakukan meeting internal unit', 'units' => '["OP", "CLERK", "MOP", "SL", "SF", "ST", "STL", "UH"]'],
            ['team' => 'TPM', 'description' => 'Melakukan tinjauan aktifitas TPM, OH dan SM-SP setiap 3 bulan', 'units' => '["STL", "UH"]'],
            ['team' => 'SM-SP', 'description' => 'Membuat laporan penggunaan expence cost bagian produksi', 'units' => '["STL", "UH"]'],
        ];

        foreach ($data as $item) {
            JobDescription::create([
                'team' => $item['team'],
                'description' => $item['description'],
                'units' => json_decode($item['units'], true)
            ]);
        }
    }
}
